// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID             int32          `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	FirstName      string         `gorm:"column:first_name;type:varchar(255);not null" json:"first_name"`
	LastName       string         `gorm:"column:last_name;type:varchar(255);not null" json:"last_name"`
	Email          string         `gorm:"column:email;type:varchar(255);not null;uniqueIndex:UQ_user_email,priority:1" json:"email"`
	Password       string         `gorm:"column:password;type:varchar(255);not null" json:"password"`
	Phone          *string        `gorm:"column:phone;type:varchar(255)" json:"phone"`
	Gender         *int32         `gorm:"column:gender;type:tinyint;default:1" json:"gender"`
	Status         *int32         `gorm:"column:status;type:int;default:1" json:"status"`
	ProfilePicture *string        `gorm:"column:profile_picture;type:varchar(255)" json:"profile_picture"`
	CreatedAt      time.Time      `gorm:"column:created_at;type:datetime;not null" json:"created_at"`
	UpdatedAt      *time.Time     `gorm:"column:updated_at;type:datetime" json:"updated_at"`
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at;type:datetime" json:"deleted_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
